### ISSUE TITLE
Некорректное описание

### ISSUE THREAD

**Issue by bullbesh** [bullbesh/persistence#15]
Не совсем понимаю, что ключевой актив компании - «Череповецкий металлургический комбинат», забыл в описании предприятия «Северсталь Российская сталь». Объясните пожалуйста (даже если они и взаимосвязаны, я считаю что лучше будет поставить информацию про «Северсталь Российская сталь» в начало описания, а уже потом добавить информацию про «Череповецкий металлургический комбинат»)

![image](https://user-images.githubusercontent.com/69913622/127373389-73358269-0df0-4128-ae01-cb8a84573e2d.png)

**Comment by Masynchin** [comment]
@BobaUbisoft17 к вам вопрос

**Comment by BobaUbisoft17** [comment]
Всё это описание было скопировано с сайта Северстали, или Википедии
+ Если мы описываем компанию нужно, как минимум, указать её основное/ые предприятие/я или фелиал(ы)

**Comment by Masynchin** [comment]
> + Если мы описываем компанию нужно, как минимум, указать её основное/ые предприятие/я или фелиал(ы)

Здравствуйте, Феликс Брых

**Comment by bullbesh** [comment]
> Всё это описание было скопировано с сайта Северстали, или Википедии
> + Если мы описываем компанию нужно, как минимум, указать её основное/ые предприятие/я или фелиал(ы)

Значит у сайта Северстали или Википедии странно написано описание «Северсталь Российская Сталь», ну или просто выдернуто из контекста оно. Всё же, идея поменять местами эти два предложения, как по мне, имеет смысл

**Comment by BobaUbisoft17** [comment]
Я не против
