### ISSUE TITLE
Неиспользуемая функция

### ISSUE THREAD

**Issue by bullbesh** [bullbesh/persistence#16]
При написании докстрингов опять наткнулся на эту функцию. Раньше уже шла о ней речь, но она так и осталась нетронутая. Докстринг я конечно написал, но вот есть ли смысл её в коде вообще держать? Жду пояснений и предложений

![image](https://user-images.githubusercontent.com/69913622/127375761-e46b48df-f442-4b3a-a0ce-062062d4e0c3.png)
![image](https://user-images.githubusercontent.com/69913622/127375845-65627b11-ec96-4f16-ae39-217c0313f808.png)

**Comment by Masynchin** [comment]
Есть такая же функция, но которая вызывается при нажатии на кнопку клавы. Зачем добавлять целую команду для такого - без понятия

**Comment by bullbesh** [comment]
> Есть такая же функция, но которая вызывается при нажатии на кнопку клавы. Зачем добавлять целую команду для такого - без понятия

Функция - домой? Или не домой

**Comment by Masynchin** [comment]
> Функция - домой? Или не домой

Функция помощи

**Comment by bullbesh** [comment]
> Функция помощи

Значит удаляю эту функцию в следующем пулл-реквесте

**Comment by bullbesh** [comment]
> > Функция помощи
> 
> Значит удаляю эту функцию в следующем пулл-реквесте
